apiVersion: apps/v1
kind: Deployment
metadata:
   creationTimestamp: null
   labels:
      app: test
   name: test
spec:
   replicas: 1
   selector:
      matchLabels:
         app: test
   strategy: {}
   template:
      metadata:
         creationTimestamp: null
         labels:
            app: test
      spec:
        runtimeClassName: gvisor       # ADD THIS
        containers:
         - image: nginx
         name: nginx
         resources: {}
status: {}

