apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-cluster-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - psp-example.      # put psp name 
